using System;

try
{
    Console.Write('a' + 'a');
}
catch (Exception)
{
    Console.WriteLine("Exception");
}
finally
{
    Console.WriteLine("Finally");
}
